# [dein.toml]

[[plugins]]
repo = 'akiya64/soifon'
hook_add = 'colorscheme soifon'

[[plugins]]
repo = 'nightsense/snow'

[[plugins]]
repo = 'Shougo/defx.nvim'

[[plugins]]
repo = 'Editorconfig/editorconfig-vim.git'

# auto close brace
[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
autocmd FileType php :set dictionary=C:/users/akiya/AppData/Local/nvim/dictionary/wordpress/functions.dict
autocmd FileType php :call deoplete#custom#source('dictionary', 'min_pattern_length', 4)
let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'deoplete-plugins/deoplete-dictionary'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
call denite#custom#option('default', 'prompt', '>')
call denite#custom#map('insert', "<C-n>", '<denite:move_to_next_line>')
call denite#custom#map('insert', "<C-e>", '<denite:move_to_previous_line>')
'''

[[plugins]]
repo = 'Tpope/vim-fugitive.git'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'kloppster/Wordpress-Vim-Syntax'

[[plugins]]
repo = 'vim-syntastic/syntastic'

[[plugins]]
repo = 'gko/vim-coloresque'

[[plugins]]
repo = 'lilydjwg/colorizer'

[[plugins]]
repo = 'joonty/vdebug'
hook_add='''
let g:vdebug_options= {
\    "port" : 9000,
\    "server" : '',
\    "timeout" : 20,
\    "on_close" : 'detach',
\    "break_on_open" : 1,
\    "ide_key" : '',
\    "debug_window_level" : 0,
\    "debug_file_level" : 0,
\    "debug_file" : "",
\    "watch_window_style" : 'expanded',
\    "marker_default" : '⬦',
\    "marker_closed_tree" : '▸',
\    "marker_open_tree" : '▾'
\}
'''

[[plugins]]
repo = 'Itchyny/lightline.vim.git'
hook_add = '''
let g:lightline = {
        \ 'colorscheme': 'PaperColor',
        \ 'mode_map': {'c': 'NORMAL'},
        \ 'active': {
        \   'left': [ [ 'mode', 'paste' ], [ 'fugitive', 'filename',  'readonly' ] ,[ 'ale' ] ],
        \   'right': [ [ 'percent', 'lineinfo' ], [ 'filetype' ], [  'fileencoding', 'fileformat' ] ]
        \   },
        \ 'component_function': {
        \   'modified': 'LightLineModified',
        \   'readonly': 'LightLineReadonly',
        \   'fugitive': 'LightLineFugitive',
        \   'filename': 'LightLineFilename',
        \   'fileformat': 'LightLineFileformat',
        \   'filetype': 'LightLineFiletype',
        \   'fileencoding': 'LightLineFileencoding',
        \   'mode': 'LightLineMode',
        \   'ale': 'AleSt'
        \   }
        \ }

function! LightLineModified()
  return &ft =~ 'help\|vimfiler\|gundo' ? '' : &modified ? '+' : &modifiable ? '' : '-'
endfunction

function! LightLineReadonly()
  return &ft !~? 'help\|vimfiler\|gundo' && &readonly ? 'x' : ''
endfunction

function! LightLineFilename()
  return ('' != LightLineReadonly() ? LightLineReadonly() . ' ' : '') .
        \ (&ft == 'vimfiler' ? vimfiler#get_status_string() :
        \  &ft == 'vimshell' ? vimshell#get_status_string() :
        \ '' != expand('%:t') ? expand('%:t') : '[No Name]') .
        \ ('' != LightLineModified() ? ' ' . LightLineModified() : '')
endfunction

function! LightLineFugitive()
  try
    if &ft !~? 'vimfiler\|gundo' && exists('*fugitive#head')
      return fugitive#head()
    endif
  catch
  endtry
  return ''
endfunction

function! LightLineFileformat()
  return winwidth(0) > 70 ? &fileformat : ''
endfunction

function! LightLineFiletype()
  return winwidth(0) > 70 ? (strlen(&filetype) ? &filetype : 'no ft') : ''
endfunction

function! LightLineFileencoding()
  return winwidth(0) > 70 ? (strlen(&fenc) ? &fenc : &enc) : ''
endfunction

function! LightLineMode()
  return winwidth(0) > 60 ? lightline#mode() : ''
endfunction
'''