# [dein.toml]
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

#colors
[[plugins]]
repo = 'akiya64/soifon'
hook_add = 'colorscheme soifon'

[[plugins]]
repo = 'chiendo97/intellij.vim'

[[plugins]]
repo = 'nightsense/snow'

[[plugins]]
repo = 'Editorconfig/editorconfig-vim'

[[plugins]]
repo = 'tyru/eskk.vim'
hook_add = '''
let g:eskk#directory = "~/.config/eskk"
let g:eskk#dictionary = { 'path': "~/.config/fcitx/user.dict", 'sorted': 1, 'encoding': 'euc-jp',}
let g:eskk#large_dictionary = {'path': "~/.config/eskk/SKK-JISYO.L", 'sorted': 1, 'encoding': 'euc-jp',}
'''

[[plugins]]
repo = 'mattn/emmet-vim'

# auto close brace
[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'Shougo/defx.nvim'

[[plugins]]
repo = 'deoplete-plugins/deoplete-dictionary'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
autocmd FileType php :set dictionary=C:/users/akiya/AppData/Local/nvim/dictionary/wordpress/functions.dict
autocmd FileType php :call deoplete#custom#source('dictionary', 'min_pattern_length', 4)
let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
call denite#custom#option('default', 'prompt', '>')
call denite#custom#map('insert', "<C-n>", '<denite:move_to_next_line>')
call denite#custom#map('insert', "<C-e>", '<denite:move_to_previous_line>')
'''

[[plugins]]
repo = 'tpope/vim-fugitive.git'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'kloppster/Wordpress-Vim-Syntax'

[[plugins]]
repo = 'vim-syntastic/syntastic'
hook_add='''
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
'''

[[plugins]]
repo= 'dense-analysis/ale'
hook_add = '''
let g:ale_linters = {
\ 'css': ['stylelint'],
\ 'javascript': ['eslint']
\ }
let g:ale_fixers = {
\ 'javascript': ['eslint']
\}
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 0
'''

[[plugins]]
repo = 'joonty/vdebug'
hook_add='''
let g:vdebug_options= {
\    "port" : 9000,
\    "server" : '',
\    "timeout" : 20,
\    "on_close" : 'detach',
\    "break_on_open" : 1,
\    "ide_key" : '',
\    "debug_window_level" : 0,
\    "debug_file_level" : 0,
\    "debug_file" : "",
\    "watch_window_style" : 'expanded',
\    "marker_default" : '⬦',
\    "marker_closed_tree" : '▸',
\    "marker_open_tree" : '▾'
\}
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = 0

[[plugins]]
repo = 'Itchyny/lightline.vim'
hook_add = '''
let g:lightline = {
        \ 'colorscheme': 'one',
        \ 'mode_map': {'c': 'NORMAL'},
        \ 'active': {
        \   'left': [ [ 'mode', 'paste' ], [ 'coc', 'fugitive', 'filename',  'readonly' ] ],
        \   'right': [ [ 'percent', 'lineinfo' ], [ 'filetype' ], [  'fileencoding', 'fileformat' ] ]
        \   },
        \ 'component_function': {
        \   'modified': 'LightLineModified',
        \   'readonly': 'LightLineReadonly',
        \   'fugitive': 'LightLineFugitive',
        \   'filename': 'LightLineFilename',
        \   'fileformat': 'LightLineFileformat',
        \   'filetype': 'LightLineFiletype',
        \   'fileencoding': 'LightLineFileencoding',
        \   'mode': 'LightLineMode',
        \   }
        \ }

function! LightLineModified()
return &ft =~ 'help\|vimfiler\|gundo' ? '' : &modified ? '+' : &modifiable ? '' : '-'
endfunction

function! LightLineReadonly()
  return &ft !~? 'help\|vimfiler\|gundo' && &readonly ? 'x' : ''
endfunction

function! LightLineFilename()
  return ('' != LightLineReadonly() ? LightLineReadonly() . ' ' : '') .
        \ (&ft == 'vimfiler' ? vimfiler#get_status_string() :
        \  &ft == 'vimshell' ? vimshell#get_status_string() :
        \ '' != expand('%:t') ? expand('%:t') : '[No Name]') .
        \ ('' != LightLineModified() ? ' ' . LightLineModified() : '')
endfunction

function! LightLineFugitive()
  try
    if &ft !~? 'vimfiler\|gundo' && exists('*fugitive#head')
      return fugitive#head()
    endif
  catch
  endtry
  return ''
endfunction

function! LightLineFileformat()
  return winwidth(0) > 70 ? &fileformat : ''
endfunction

function! LightLineFiletype()
  return winwidth(0) > 70 ? (strlen(&filetype) ? &filetype : 'no ft') : ''
endfunction

function! LightLineFileencoding()
  return winwidth(0) > 70 ? (strlen(&fenc) ? &fenc : &enc) : ''
endfunction

function! LightLineMode()
  return winwidth(0) > 60 ? lightline#mode() : ''
endfunction
'''